version: 2
jobs:
  build:
    docker:
      - image: cypress/base:8
    working_directory: ~/origin
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Installation
          command: npm i
      - run:
          name: Lint
          command: npm lint
      - run:
          name: Running Unit Tests
          command: npm run test
      - run:
          name: Running E2E tests
          command: npm run test:e2e

workflows:
  version: 2

  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - /feat\/.*/
            tags:
              only: /^v.*/
